Repository NadyaHuryan/FE30, pull requests merged in 2022-06, with the labels that each got.

#8 Matusevich Philippe(hw_1)
  lesson-1/hw_1.js
Labels: done

#9 Aleksandrs Gluhovs [hw_1]: My first pull request
  lesson-1/hw_1.js
Labels: done

#17 Lizaveta Lazarchuk [hw_1]: My first pull request
  lesson-1/hw_1.js
Labels: done

#11 Vadim Homutovsky [hw_2]: the second pull request and solved tasks
  forCheckJsConsole.html
  js/hw_1.js
  js/hw_2.js
  lesson-2/hw-2.md
Labels: done, comments in code

#12 Tilegen Bakitov[hw_2]: HomeWork2 Done
  lesson-2/hw-2.js
  lesson-2/hw-2.md
  lesson-2/index.html
Labels: done, comments in code

#13 Vitaliy Kharlamov [hw_2]: Did second homework
  lesson-2/hw-2.md
  lesson-2/hw_2.js
  lesson-2/index-hw_2.html
Labels: done

#15 Vitali Danilevich hw 2
  .DS_Store
  lesson-1/hw_1.js
  lesson-2/hw-2.md
  lesson-2/hw_2.html
  lesson-2/hw_2.js
Labels: done

#16 Aleksandrs Gluhovs(hw_2): Homework 2
  lesson-2/hw_2.js
  lesson-2/index.html
Labels: done, comments in code

#18 Margarita Karelina [hw_1]: My first pull request
  lesson-1/hw_1.js
Labels: done, comments in code

#21 Mikhail.mikhan hw 2
  lesson-2/hw-2.md
  lesson-2/hw_2.js
  lesson-2/index.html
Labels: done, comments in code

#20 init(hw_2): done the second home work
  lesson-2/hw-2.js
  lesson-2/hw-2.md
  lesson-2/index.html
Labels: done, comments in code

#24 init(hw_2): homework 2 (second try)
  lesson-2/hw_2.js
Labels: done

#26 Masha.loiko[hw-2]: add homework-2
  lesson-2/hw-2.md
  lesson-2/hw_2.js
  lesson-2/index-hw_2.html
Labels: done, comments in code

#27 Aleksey Cheronko [hw_2]: Add my HomeWork 2
  lesson-2/hw-2.md
  lesson-2/hw_2.js
  lesson-2/index.html
Labels: done, comments in code

#28 Matusevich.philippe hw 2
  lesson-1/hw_1.js
  lesson-2/index.html
  lesson-2/index.js
Labels: done, comments in code

#30 Hutsau Aliaksandr(hw_1): start course Javascript Basic
  lesson-1/hw_1.js
Labels: done

#23 Bylitski.mikhail
  lesson-2/hw-2.md
  lesson-2/index.html
  lesson-2/js/index.js
  prepros.config
Labels: need to fix, ready for review, done, comments in code

#29 Margarita Karelina [hw_2]: fix tasks 1 and 3
  lesson-2/hw_2.js
Labels: done

#33 Alexey.potapcev hw 2
  lesson-2/hw-2.md
  lesson-2/index.html
  lesson-2/js/hw_2.js
Labels: done, comments in code

#38 залил ДЗ исправил
  lesson-1/hw-1.md
  lesson-2/index.html
  lesson-2/index.js
  lesson-3/hw-3.md
  lesson-4/hw-4.md
Labels: done, comments in code

#34 Vadim.homutovsky hw 3
  html/hw_2.html
  html/hw_3.html
  js/hw_3.js
  lesson-1/hw-1.md
  lesson-3/hw-3.md
Labels: done, comments in code

#35 Vitaliy kharlamov [hw 3]: add three home work
  lesson-1/hw-1.md
  lesson-3/hw-3.md
  lesson-3/hw_3.js
  lesson-3/index-hw_3.html
Labels: done, comments in code

#44 Matusevich Philippe [hw_2]: Fix
  lesson-2/index.js
Labels: ready for review

#37 Lizaveta.lazarchuk hw 3
  lesson-1/hw-1.md
  lesson-3/hw-3.js
  lesson-3/hw-3.md
  lesson-3/index.html
Labels: done

#45 Vadim Homutovsky fix[hw-3]: correct extra wrongs
  js/hw_3.js
Labels: ready for review

#42 Margarita Karelina [hw_3]: fix hw_3
  lesson-1/hw-1.md
  lesson-1/hw_1.js
  lesson-2/hw_2.js
  lesson-3/hw-3.md
  lesson-3/hw_3.js
  lesson-3/index.html
  lesson-4/hw-4.md
Labels: done

#48 Hutsau Aliaksandr [hw_2]: My second pull request
  lesson-2/hw_2.js
  lesson-2/index.html
Labels: done, comments in code

#36 Masha.loiko [hw-3]: add homework 3
  lesson-1/hw-1.md
  lesson-3/hw-3.md
  lesson-3/hw_3.js
  lesson-3/index.html
  lesson-4/hw-4.md
Labels: need to fix, ready for review, comments in code

#41 Aleksandrs.gluhovs hw 3
  lesson-1/hw-1.md
  lesson-2/hw-2.md
  lesson-3/hw-3.md
  lesson-3/hw_3.js
  lesson-3/index.html
  lesson-4/hw-4.md
Labels: ready for review

#43 Tilegen Bakitov[hw_3]: HomeWork3 Normal Level Done
  .DS_Store
  lesson-1/hw-1.md
  lesson-3/hw-3.js
  lesson-3/hw-3.md
  lesson-3/index.html
  lesson-4/hw-4.md
Labels: ready for review

#49 Hutsau Aliaksandr[hw-2]: corrected task five
  lesson-2/hw_2.js
Labels: done

#40 Aleksey Cheronko [hw_3]: add part homework 3
  lesson-1/hw-1.md
  lesson-3/hw-3.md
  lesson-3/hw_3.js
  lesson-3/index.html
  lesson-4/hw-4.md
Labels: done

#54 Alexey.potapcev hw 3
  lesson-1/hw-1.md
  lesson-3/hw-3.md
  lesson-3/index.html
  lesson-3/js/script.js
Labels: done, comments in code

#52 Margarita Karelina [hw_4]: do hw 4
  lesson-3/hw_3.js
  lesson-4/hw_4.js
  lesson-4/index.html
Labels: ready for review

#51 Vitaliy Kharlamov [hw_4]: did fourth homework
  lesson-3/hw_3.js
  lesson-4/hw-4.md
  lesson-4/hw_4.js
  lesson-4/index-hw_4.html
Labels: done

#50 Hutsau Aliaksandr [hw_3]: My third pull request
  lesson-3/hw-3.md
  lesson-3/hw_3.js
  lesson-3/index.html
  lesson-4/hw-4.md
Labels: need to fix, ready for review

#59 init(hw_4): Tasks 1-8
  .vscode/settings.json
  lesson-4/hw_4.js
  lesson-4/index.html
Labels: done, comments in code
